name: dating
description: A new Flutter application.


publish_to: "none" # Remove this line if you wish to publish to pub.dev


version: 1.0.4+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  firebase_auth:
  cloud_firestore:
  provider: ^5.0.0
  flutter_spinkit: ^4.1.2+1
  firebase_core: ^0.5.3
  firebase_storage:
  shared_preferences: ^0.5.12+4
  pin_code_fields: 5.2.0
  spring_button: ^1.0.14
  multi_masked_formatter: ^0.1.1
  flutter_svg:
  image_picker: ^0.6.7+21
  smooth_page_indicator: ^0.1.5
  firebase_messaging: ^7.0.3
  bubble: ^1.1.9+1
  url_launcher: ^5.6.0
  cached_network_image: ^2.5.0
  intl: ^0.16.1
  intl_phone_field: ^2.0.0
  shimmer: ^1.1.2
  network_to_file_image: ^2.3.8
  lottie: ^0.7.0+1
  mailer:
  permission_handler:
  just_audio:
  flutter_sound:

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/lottie/
    - assets/logo/
    - assets/icons/navigation/
    - assets/boarding/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
